(define make-vect cons)
(define xcor-vect car)
(define ycor-vect cdr)
(define (add-vect a b)
  (make-vect (+ (xcor-vect a)
                (xcor-vect b))
             (+ (ycor-vect a)
                (ycor-vect b))))
(define (sub-vect a b)
  (make-vect (- (xcor-vect a)
                (xcor-vect b))
             (- (ycor-vect a)
                (ycor-vect b))))
(define (scale-vect a s)
  (make-vect (* (xcor-vect a)
                s)
             (* (ycor-vect a)
                s)))

(display (add-vect (make-vect 1 2) (make-vect 4 5)))
(newline)
(display (sub-vect (make-vect 4 5) (make-vect 1 2)))
(newline)
(display (scale-vect (make-vect 1 2) 3))
(newline)
