(define (base frame) (origin frame))
(define (right frame) (add-vector (base frame) (edge1 frame)))
(define (left frame) (add-vector (base frame) (edge2 frame)))
(define (top frame) (add-vector (right frame) (edge2 frame)))

(define (frame-painter frame)
  (let ((b (make-segment (base frame) (right frame)))
        (l (make-segment (base frame) (left-frame)))
        (t (make-segment (left-frame) (top-frame)))
        (r (make-segment (right-frame) (top-frame))))
    ((segments->painter (list b l t r)) frame)))

(define (x-painter frame)
  (let ((h (make-segment (left frame) (right frame)))
        (v (make-segment (base frame) (top-frame))))
    ((segments->painter (list h v)) frame)))

(define (middle-painter frame)
  (let ((b (/ (add-vector (base frame) (right frame)) 2))
        (l (/ (add-vector (base frame) (left frame)) 2))
        (t (/ (add-vector (left frame) (top frame)) 2))
        (r (/ (add-vector (right frame) (top frame)) 2)))
    ((segments->painter (list (make-segment b r)
                              (make-segment b l)
                              (make-segment l t)
                              (make-segment r t)))
     frame)))
