(define tolerance 0.00001)
(define (average x y) (/ (+ x y) 2))
(define (fixed-point f first-guess)
  (define i 0)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (set! i (+ i 1))
      (display i)
      (display "     ")
      (display next) (newline)
      (if (close-enough? guess next)
        next
        (try next))))
  (try first-guess))
(fixed-point (lambda (x) (/ (log 1000) (log x))) 2.0)
; 34 guesses without average damping
(fixed-point (lambda (x) (average x (/ (log 1000) (log x)))) 2.0)
; 9 guesses with average damping
