(define (make-account balance password)
  (let ((bad-passwords 0))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch p m)
      (if (not (eq? p password))
        (begin (set! bad-passwords (+ bad-passwords 1))
               (if (< 7 bad-passwords)
                 (lambda (x) 'call-the-cops)
                 (lambda (x) "Incorrect password")))
        (begin (set! bad-passwords 0)
               (cond ((not (eq? p password)) (lambda (x) "Incorrect password"))
                     ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT" m))))))
    dispatch))

(define (make-joint acc old-pass new-pass)
  (lambda (p m)
    (if (eq? p new-pass)
      (acc old-pass m)
      (lambda (x) "Incorrect password"))))

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
(define joint (make-joint acc 'secret-password 'new-password))
((joint 'new-password 'withdraw) 20)
((joint 'bad-password 'withdraw) 20)
